// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgou1qGFPYtRYhat4U0xsfNhzHPZPuTAY',
    appId: '1:365758035398:web:8a35d1b6875b726292aec7',
    messagingSenderId: '365758035398',
    projectId: 'zenzone-b4685',
    authDomain: 'zenzone-b4685.firebaseapp.com',
    storageBucket: 'zenzone-b4685.appspot.com',
    measurementId: 'G-FRTNKJS4RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqcNM8tMa_7PFZ7AN9ipQ-W1bfwvyofGk',
    appId: '1:365758035398:android:6e7c38994173e72c92aec7',
    messagingSenderId: '365758035398',
    projectId: 'zenzone-b4685',
    storageBucket: 'zenzone-b4685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBODNN1WlfRKlARbDADv7IgacWGuRL4Mcg',
    appId: '1:365758035398:ios:014e4c979669333092aec7',
    messagingSenderId: '365758035398',
    projectId: 'zenzone-b4685',
    storageBucket: 'zenzone-b4685.appspot.com',
    androidClientId: '365758035398-kil17qe5tct7a3patpodl4vrr6jsckd5.apps.googleusercontent.com',
    iosClientId: '365758035398-klqsf8fkbicv7ht1qup8d1vqgqe8219p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBODNN1WlfRKlARbDADv7IgacWGuRL4Mcg',
    appId: '1:365758035398:ios:db7e53740513cf6792aec7',
    messagingSenderId: '365758035398',
    projectId: 'zenzone-b4685',
    storageBucket: 'zenzone-b4685.appspot.com',
    androidClientId: '365758035398-kil17qe5tct7a3patpodl4vrr6jsckd5.apps.googleusercontent.com',
    iosClientId: '365758035398-8gqhl10han00opdcf2m1vbcbs6e3u3k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom.RunnerTests',
  );
}
